package year2018.puzzle9;

/**
 * Part A: 409832
 *
 * This was generated by AI and much much faster.
 */
public class Puzzle9B {

    static final int numberOfPlayers = 428;
    static final int numberOfMarbles = 7206100;

    // Use primitive arrays for performance:
    // - next[i] and prev[i] store the clockwise/counter-clockwise neighbors of marble i
    // - scores[playerIndex] stores the accumulated score for players (0-based)
    static void main() {
        final int maxMarble = numberOfMarbles;
        int[] next = new int[maxMarble + 1];
        int[] prev = new int[maxMarble + 1];
        long[] scores = new long[numberOfPlayers];

        // initialize circular list with marble 0
        next[0] = 0;
        prev[0] = 0;
        int current = 0;

        for (int m = 1; m <= maxMarble; m++) {
            if (m % 100000 == 0) {
                System.out.println("Marble " + m);
            }

            if (m % 23 == 0) {
                int player = (m - 1) % numberOfPlayers; // 0-based player index
                scores[player] += m;

                // move 7 counter-clockwise (prev)
                int remove = current;
                for (int k = 0; k < 7; k++) {
                    remove = prev[remove];
                }

                // add removed marble's value
                scores[player] += remove;

                // unlink 'remove' from circle
                int before = prev[remove];
                int after = next[remove];
                next[before] = after;
                prev[after] = before;

                // current becomes the marble clockwise of the removed one
                current = after;
            } else {
                // insert new marble between next[current] and next[next[current]]
                int a = next[current];
                int b = next[a];

                next[a] = m;
                prev[m] = a;
                next[m] = b;
                prev[b] = m;

                current = m;
            }
        }

        long best = 0L;
        for (long s : scores) {
            if (s > best) {
                best = s;
            }
        }
        System.out.println("Part A: " + best);
    }
}
